version: '3.9'

services: 
  nodeapp:
    build:
      context: .
    restart: always
    ports:
      - 5000:5000

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
 
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: oluet_api_dev
    ports:
     - 5432:5432
  

