import { objectType } from '@nexus/schema'

export const JuomaT = objectType({
   name: 'Juoma',
   definition(t) {
      t.id('id')
      t.string('productId')
      t.string('nimi')
      t.string('valmistaja')
      t.string('pulloKoko')
      t.string('hinta')
      t.string('litraHinta')
      t.string('tyyppi')
      t.string('alaTyyppi', { nullable: true })
      t.string('erityisryhma', { nullable: true })
      t.string('olutTyyppi', { nullable: true })
      t.string('valmistusMaa')
      t.string('alue')
      t.string('vuosikerta')
      t.string('etikettimerkintoja', { nullable: true })
      t.string('huomautus', { nullable: true })
      t.string('rypaleet', { nullable: true })
      t.string('luonnehdinta')
      t.string('pakkausTyyppi')
      t.string('suljentaTyyppi')
      t.string('alkoholiProsentti')
      t.string('hapotGL')
      t.int('sokeriGL')
      t.string('kantavierrep', { nullable: true })
      t.string('katkerot', { nullable: true })
      t.string('energia100ML', { nullable: true })
      t.string('valikoima', { nullable: true })
      t.string('EAN', { nullable: true })
   },
})
