apiVersion: apps/v1
kind: Deployment
metadata:
  name: oluet-api
  namespace: oluet-api
  labels:
    app: oluet-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oluet-api
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: oluet-api
        image: oluet-api:latest
        env:
        - name: PORT
          value: "5000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: oluet-api-env
              key: DATABASE_URL
        ports:
        - containerPort: 5000
        resources: {}


---
kind: Service
apiVersion: v1
metaData:
  name: oluet-api
  namespace: oluet-api
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 5000