---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  namespace: oluet-api
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 5Gi

---
kind: Deployment
apiVersion: apps/v1
metaData:
  name: postgres
  namespace: oluet-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: olue-api-env
                    key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                  secretKeyRef:
                    name: oluet-api-env
                    key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                  secretKeyRef:
                    name: oluet-api-env
                    key: POSTGRES_DB
          volumeMounts:
            - mountPath: /var/lib/postgres/
              name: database
          resources:
              limits:
                cpu: '500m'
                memory: '256Mi'
              requests:
                cpu: '250m'
                memory: '256Mi'
      volumes:
        - name: database
          persistentVolumeClaim:
              claimName: postgres-pvc  


---
kind: Service
apiVersion: v1
metadata:
  name: postgres
  namespace: oluet-api
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432

    