kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  namespace: oluet-api
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  namespace: oluet-api
spec:
  storageClassName: manual
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 5Gi

---
kind: Deployment
apiVersion: apps/v1
metaData:
  name: postgres
  namespace: oluet-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: olue-api-env
                    key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                  secretKeyRef:
                    name: oluet-api-env
                    key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                  secretKeyRef:
                    name: oluet-api-env
                    key: POSTGRES_DB
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: database
          resources: {}
      volumes:
        - name: database
          persistentVolumeClaim:
              claimName: postgres-pvc  


---
kind: Service
apiVersion: v1
metadata:
  name: postgres
  namespace: oluet-api
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres

    
